### ISSUE TITLE
Has anyone gotten around the 403 server response?

### ISSUE THREAD

**Issue by ghost** [IvRogoz/Scrape_IMDB#1]
I tried adding a User-Agent via building a Request object and passing that to urlopen().

No luck; it tries, but IMDb still returns 403.

Has anyone had any success with this?

**Comment by ghost** [comment]
I'll leave some info here for anyone who decided to actually read these.

  I tried randomized User-Agents, but by that time, I'd been blocked, so, no luck.

  I'm now using a scraper proxy and can get a 200 response and the htmldata for a given gallery based on the movieID provided as an argument. This required moving from urllib.urlopen() to using the Requests libs' requests.get(); took some fiddling.

  However, each individual image download still gets a 400 from the server(s). I'm not sure yet if the problem is in my code or is on the server side, and therefore unavoidable.

  If I get a working version, I will, of course share my changes.

**Comment by ghost** [comment]
I could be mistaken, but it seems that IMDb has made some changes since this was first written. The URL to the large images is no longer in the response data. Instead, the mediaviewer is called for the image.

I'm not seeing how to extract the large image URL, but it would be great if it was doable.

**Comment by ghost** [comment]
After analyzing the IMDb's html, I found the new way to get the image gallery large images.

I have a modified version of scrapeIMDB_gallery.py which works as of 6 October 2023. I've included Cinemagoer libraries so as to get IMDb movieID from a movie title. I've also implemented the use of a scraper proxy to keep IMDb happy.

I will make this available, but I wish to contact IvRogoz. Can't seem to do that easily. Meanwhile, for anyone who may actually read this, here is a quick summary of my version:

 This is a modified version of scrapIMDB_gallery from https://github.com/IvRogoz
 (License ??)
 
 Modified  Sep/Oct 2023 by https://github.com/jfadams1963:
 + Named this version imdb_gallery_scrape.py
 + Made changes to reflect the new structure on IMDb.
 + Added Cinemagoer functionality.
 + Modified requests to go through a scraper proxy to keep IMDb happy.
   ->Get a free API key at https://scrapeops.io/
 + Using SoupStrainer for more efficient html parsing.
 + Using settings for API_KEY (optional)
 + Usage:
     imdb_gallery_scrape.py movie <title|movieID>
     imdb_gallery_scrape.py actor|person <name|personID>

**Comment by ghost** [comment]
https://github.com/jfadams1963/IMDb_Gallery_Scrape

**Comment by IvRogoz** [comment]
Sorry for not responding sooner.
 Work got in the way of checking my private email. I see you managed to figure it out on your own :)

**Comment by ghost** [comment]
Hey, great to hear from you! I really enjoyed the process of getting it to work given the changes on the IMDb side of things.

I would really like to put my changed version under the 2-clause BSD license; just a personal pref. If you have another preference (MIT?) please let me know and I will honor that. Please let me know when you have time.

Thanks for all the work you put into the scraper. It's fun to play with! ;-)

**Comment by ghost** [comment]
puff... been tought to keep up with everything. 
Nice to see people find some of my musings interesting :) 
Ive added 2-clause BSD license to the project. 

Recently I had to do some scraping of images from a website that did not alow it directly from python, nothing helped, not requests, not puppetier, nothing. I then noticed that wget was managing it when I tried it directly from the terminal, which was wierd as I did not remember installing wget. It turned out wget was maped by default in powershell to Invoke xyz...  so this  managed to do it via subprocess and powershell:
command = [
            "powershell",
            "-Command",
            f"Invoke-WebRequest -Uri '{url}' -OutFile '{file_name}'"
        ]
        try:
            subprocess.check_call(command)
            print(f"Downloaded {url} to {file_name}")
        except subprocess.CalledProcessError:
            print(f"Error downloading {url}")

Just a tip!

**Comment by ghost** [comment]
Thanks for the tip; these little things are often useful to have in the tool kit.

And thanks for letting me know about the license. I will update when I have some time today.

Be well! :-)
